### ISSUE TITLE
Fails to compile: EventChannel and MetaDataDescriptorArray not defined, etc

### ISSUE THREAD

**Issue by e-matteson** [tne-lab/crossing-detector#1]
Trying to compile the plugin gives the following errors:

    In file included from CrossingDetectorEditor.cpp:24:0:
    CrossingDetector.h: At global scope:
    CrossingDetector.h:137:5: error: ‘EventChannel’ does not name a type; did you mean ‘pEventChan’?
         EventChannel* eventChannelPtr;
         ^~~~~~~~~~~~
         pEventChan
    CrossingDetector.h:138:5: error: ‘MetaDataDescriptorArray’ does not name a type
         MetaDataDescriptorArray eventMetaDataDescriptors;
         ^~~~~~~~~~~~~~~~~~~~~~~
    CrossingDetector.h:75:10: error: ‘void CrossingDetector::createEventChannels()’ marked ‘override’, but does not override
         void createEventChannels() override;
              ^~~~~~~~~~~~~~~~~~~
    CrossingDetector.h:77:10: error: ‘void CrossingDetector::process(juce::AudioSampleBuffer&)’ marked ‘override’, but does not override
         void process(AudioSampleBuffer& continuousBuffer) override;

This is with plugin-GUI commit 7289059d (v0.4.2), on linux. Grep agrees that `EventChannel`, `MetaDataDescriptorArray` and `createEventChannels` don't appear anywhere else in the plugin-GUI source.

Thanks for contributing this plugin, it looks very useful and I'm excited to try it out!

**Comment by ethanbb** [comment]
Hey, thanks for pointing this out. I forgot to mention that the plugin uses the [new data and channel objects](https://open-ephys.atlassian.net/wiki/display/OEW/Data+and+channel+objects?src=contextnavpagetreemode), so it will only compile with what is currently the development branch of the GUI (but will hopefully be merged into master before too long). I'll update the readme etc. to reflect this.

**Comment by e-matteson** [comment]
Works for me on the development branch. Thanks!
