### ISSUE TITLE
TTL out?

### ISSUE THREAD

**Issue by pplenck** [tne-lab/crossing-detector#4]
Hello
this may sound like a stupid question but how do we now it works? 
when open-ephys receives TTLS, it displays a colored band on the LFP display. I am asking this for two reasons:
-I am using the rhd2000 from intan and I have access to 16 digial out and 8 analog out channels. so when you show 8 TTL channels I get confused to which channel we are talking about. I just downloaded the plugin from the last version of open-ephys. 
my goal is to send a TTL pulse to initiate a matlab driven sequence of behavioral events.
-what are the units for the threshold detection ? Volts seem rather big since most of us have a max of 1mV range of data
Thank you for your help and this nice plugin
Pepe

**Comment by ethanbb** [comment]
Hi Pepe,

Good questions, thanks for asking.

- The 8 channels shown in the LFP viewer correspond to digital **inputs** on the acquisition board. The Crossing Detector can also write to its own set of 8 purely software TTL channels, which will also show up on the LFP viewer.
    - So if you have both hardware TTL pulses coming in on digital input 1 and the Crossing Detector outputting on its channel 1, both types of event will show up as channel 1 on the LFP viewer and it'll be ambiguous which are which. However, the recorded event data includes information about which processor produced each event, and so does the event object you would read to trigger things in Open Ephys or other software, so it's only an issue for visualization. 
- Unfortunately there's no capability to output the events on hardware digital out channels. See [this page](https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/491613/How+it+works) (which is about the OEP acquisition board but I believe equally applies to the RHD2000): "The digital outputs are not yet part of the Open Ephys software."
- However, if you want to trigger an event in MATLAB, you can use the [Event Broadcaster](https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Event-Broadcaster.html) sink, which broadcasts all events using ZeroMQ to be received by any other program on your local computer that is listening. (Is this not built-in anymore?) It uses the publish/subscribe pattern and you may have to figure out how to set up your MATLAB code to subscribe to the events yourself - there is an example of request/response in Resources/Matlab of the GUI source code (which is for the Network Events source), but not for pub/sub. There is a pub/sub example under Python called `event_listener.py` that you could use as a guide, though.
- You're right, the threshold is not necessarily volts - it's whatever the "natural" unit is for the input channel. This is defined at the code level but I'm not sure it's obvious in the GUI. In any case I believe for normal continuous data, this is uV, and if you have any analog inputs plugged in on the side those are in volts.

-Ethan

**Comment by pplenck** [comment]
ah, it saw the doc from open-ephys about digital outputs, but i thought you guys hacked it. 
do you think I can use the other plugin called "matlabinterface" 
https://github.com/medengineer/MatlabInterface/blob/master/MATLAB/API/OEClient.m
They use a java socket trick. I am not familiar with matalb doing imports like in python but it sounds cool. So I guess as you send a ttl event (I'll use the 8, since my 1-5 are used for optogenetics inputs) I can pick it up with matlab? The thing is, I don't know is how fast matlab acquires this kind of info.  
ZeroMq is new to me too but the code they gave on the github page sounds easy to handle. once you install the matlab-zeromq mexfiles, you can run stuff like:
%% MATLAB code for sending and receiving ZeroMQ data
% Setup
subscriber = zmq( 'subscribe', 'tcp', '127.0.0.1', 43210 );
publisher = zmq( 'publish', 'tcp', 43210 );

% Publish data
bytes = uint8(rand(100,1));
nbytes = zmq( 'send', publisher, bytes );

% Receive data
receiver = zmq('poll', 1000); // polls for next message
[recv_data, has_more] = zmq( 'receive', receiver );

disp(char(recv_data));

%%%
again, I don't know about the speed of acquisition.

if you have info on people who use your plugin with malab, I'm interested.
thanks for the help, it's getting clearer.

**Comment by ethanbb** [comment]
No problem!

I haven't used the matlab interface plugin before, but why not give it a try. The only thing is, it looks like they haven't implemented sending events to matlab yet - just continuous data. So you could either implement your own threshold crossing detector code in matlab using the continuous data, or you could try to modify their plugin to send/receive TTL events (but that would be a lot harder).

As for the ZMQ route, that looks like a good start! I'm don't know of anyone using matlab in their signal chain, but we used ZMQ to send events to LabVIEW and for what it's worth we never had any latency issues with the ZMQ part. 

I have some code specifically for receiving the crossing detector events, unfortunately only in Python and LabVIEW though. If you have LabVIEW, you can take a look at the VIs here: https://github.com/tne-lab/closed-loop-stim/tree/master/zmq_utilities. The Python repository is private, but here's that code (this is for JSON format events which is a bit easier in Python):

```python
import zmq
import numpy as np
from convertString import convertString
import json


def prettyJson(jsonStr, tab = ''):
    for key in jsonStr.keys():
        if type(jsonStr[key]) is dict:
            print(key + "\n", end='')
            prettyJson(jsonStr[key], tab + '\t')
        else:
            print(tab, key, ": ", convertString(jsonStr[key]))

def main():
    context = zmq.Context()

    #  Socket to listen to OE
    print("Connecting to Open Ephys...")
    socket = context.socket(zmq.SUB)
    socket.connect("tcp://localhost:5557")
    #Have to Set to the beginning for the envelope!
    socket.setsockopt(zmq.SUBSCRIBE, b'ttl')
    socket.setsockopt(zmq.SUBSCRIBE, b'spike')

    for request in range(10):
        print('waiting')

        #Get raw input from socket
        envelope, jsonStr = socket.recv_multipart()
        print(envelope)

        #Our actual json object (last part)
        jsonStr = json.loads(jsonStr);
        prettyJson(jsonStr)

        print('\n')
main()
```

**Comment by pplenck** [comment]
Sweet, I may use the labview since I drive my opto with a NI card. Can I ? I'll cite you. 
It will go faster!
Just to be clear, do you output zeromq events or do we have to use the other plugin for that?

**Comment by ethanbb** [comment]
Yes, feel free to use the LabVIEW code! You do have to put an event broadcaster after the crossing detector for it to work.

**Comment by pplenck** [comment]
Now it's the broadcaster that does not work. I can't even load it in the signal chain. have you ever had issues with it?
where do you put it in the signal chain? after your plugin?

**Comment by ethanbb** [comment]
If you're also using another sink like the lfp viewer, you have to use a splitter before it to send the signal to two different sinks. Does that help?

**Comment by pplenck** [comment]
I does, but not with the event broadcaster, which is part of another issue on the dedicated repository (I think I need to compile it on my windows7 machine). 
On your side of the business I managed to see the events on the recording (if you put the record node after your plugin). So I know the units are, as you wrote, the same as the ones we see in the LFP viewer (so it's microvolts for the LFP)
Could you add a mean to know the threshold got detected, like an LED on the front panel. It will help the user to adjust settings.
Thanks for your help!

**Comment by ethanbb** [comment]
Glad to hear things are working. That being said, the events are supposed to be visible on an LFP viewer that comes after it in the signal chain. If that's not working, the first thing to check would be that the event channel you are outputting on is enabled in the viewer.

**Comment by pplenck** [comment]
ha!! indeed it works if you pull the lfp viewer AFTER. sorry for being a dumbXXX.
It's working fine then. Figuring out the event broadcaster.
I guess you can close the issue then?

**Comment by ethanbb** [comment]
OK, great, good luck!
