### ISSUE TITLE
Reading output in matlab?

### ISSUE THREAD

**Issue by pplenck** [tne-lab/crossing-detector#5]
HI
can you give us a link to some matlab (even python) code that reads the broadcasted events?
I am stuck between jeromq, tcp ip sockets etc...
thx if you can

**Comment by ethanbb** [comment]
Hi @pplenck,

Sorry, I've never done what you're trying to do and I don't think there's a super easy way, but here's what I can say:
- The Python program I pasted in #4 should work to receive events if you set the Event Broadcaster to "Header/JSON" mode.
- Googling leads to suggestions to use jeromq, so I would keep trying that and try to translate the Python program into Java.
- The [MATLAB code](https://github.com/open-ephys/plugin-GUI/tree/master/Resources/Matlab) for request/reply included with the Open Ephys GUI seems to use a custom mexfile, which you could perhaps try to modify for pub/sub

**Comment by pplenck** [comment]
Mark Shatza helped me on this, this is in python (yeah, I gave up on matlab, I couldn't compile the jar file)

let me add the part of the code that's important,
first  eventbroadcaster is in the SUB-PUB protocol
so
 socket = context.socket(zmq.SUB)
socket.connect("tcp://127.0.0.1:5558")
#here is the key: 
    socket.setsockopt(zmq.SUBSCRIBE, b'ttl')
    socket.setsockopt(zmq.SUBSCRIBE, b'spike')
voilà!
thanks Mark
