### ISSUE TITLE
Planning to extend the plugin

### ISSUE THREAD

**Issue by cjthomas-opensource** [tne-lab/crossing-detector#6]
As a heads-up, I'm planning to add at least two things to this plugin; I'll submit a pull request when I have a local version tested and working.

Planned changes:
- Adding a "N standard deviations" threshold option.
- Augmenting the input channel selector to include the names of channels in addition to their number (and the stream number, since the mag-plus-phase detector makes a new stream).

There's a lot more than I'd _like_ to polish, but I'm under significant time constraints, so for now it'll just be the changes above. Let me know if there's anything specific that you want me to take into account when doing this.

**Comment by ethanbb** [comment]
This sounds great to me - thank you!

I can definitely relate to significant time constraints...I wanted to work on getting the adaptive threshold feature working again in the latest version of the GUI (also involving modifying the phase calculator), but I haven't gotten around to it. On the other hand, current members of the TNELab probably have a better idea of what functionality makes sense to add/update at this time.

**Comment by cjthomas-opensource** [comment]
I've submitted the pull request.

Josh says that they actually have dedicated coding staff over there now, so you might ask them about doing the port for you (folding the CD and PC in as OE-supported plugins rather than third-party).

For the phase calculator, I'm considering modifying it so that magnitude and phase _both_ go on new channels instead of having the original channel modified, but that's a low-priority task for now.

**Comment by ethanbb** [comment]
Hi Christopher, I have not found much time to work on this since November - I think trying to get OE coding staff to work on this to whatever extent they can/want to is a great idea.

**Comment by cjthomas-opensource** [comment]
I doubt that the OE people are going to do it - they seem to be focused on developing OE 0.6/0.7 and their core plugins, rather than on porting third-party plugins into Open Ephys.

Since this is a TNE Lab plugin, it would be someone from the TNE lab that makes the call. I think there's at least one active person managing the GitHub projects still.
